### ISSUE TITLE
See list of modules

### ISSUE THREAD

**Issue by tschubotz** [gnosis/safe-cli#10]
I would love to see the list of enabled modules on my Safe incl. some meta info such as module address, name etc.

**Comment by Uxio0** [comment]
Now with `info` command modules enabled for that Safe will be shown. Only information displayed will be the `address`, as I there isn't any other standard information (like module name): https://github.com/gnosis/safe-contracts/blob/development/contracts/base/Module.sol

Feel free to close the issue if that's ok for you 😃

**Comment by tschubotz** [comment]
Beautiful, I think that's cool for now :)
Thanks!
