### ISSUE TITLE
Arbitrary contract transactions

### ISSUE THREAD

**Issue by lorenzb** [gnosis/safe-cli#14]
First of all: thank you, this looks awesome!

It would be great if there were a way to add ABIs of contracts and send arbitrary transactions to them.

**Comment by Uxio0** [comment]
I already had this idea in the roadmap 😉, thanks for openning this issue @lorenzb!

**Comment by Uxio0** [comment]
Hi @lorenzb, I have just implemented a method `send_custom` to send custom transactions, so if you build the data yourself you can use it with the **Safe cli**. `Delegatecalls` are also supported
