### ISSUE TITLE
Display some status outuput when loading a Safe

### ISSUE THREAD

**Issue by tschubotz** [gnosis/safe-cli#17]
When I load a Safe, e.g. `python safe_cli.py 0x9D2407C6b6c1C307AB54Adb01627Ba0845e3Cddf https://rinkeby.infura.io/v3/`

It takes for me several seconds until the cli is opened. I assume that RPC calls are made to load all required info.

Would it make sense to show either a loading bar or some verbose output what info is current pulled? That would give me the feeling that something is in the works. Otherwise I'm unsure if it's maybe blocked.

**Comment by Uxio0** [comment]
As I retrieve all together using batching (so it's everything or nothing) for now I would just display a "Loading info prompt" until I implemented something fancier, I leave this opened 🙂
