### ISSUE TITLE
Connecting to contracts - ValueError: getOwners

### ISSUE THREAD

**Issue by JosephBagaric** [gnosis/safe-cli#28]
I've deployed the v1.1.1 contracts to the **Volta testnet** using Truffle (`yarn truffle deploy`)

```
    volta: {
      provider: () => {
        return new HDWalletProvider(mnemonic, 'https://volta-rpc.energyweb.org')
      },
      network_id: '73799',
      gasPrice: 1
    }
```

 and verified on the Volta block explorer (links included).

GnosisSafeProxyFactory: [0x15cbA3FCAa2D1A03fD84D10D2F290e74535E3d7B](https://volta-explorer.energyweb.org/address/0x15cba3fcaa2d1a03fd84d10d2f290e74535e3d7b/contracts)
CreateAndAddModules: [0xCde77B42c294e293eA64492aA3cB836396E491eb](https://volta-explorer.energyweb.org/address/0xcde77b42c294e293ea64492aa3cb836396e491eb/contracts)
MultiSend: [0x8311e46d637607E42fBd595DD2fDff130a94110e](https://volta-explorer.energyweb.org/address/0x8311e46d637607e42fbd595dd2fdff130a94110e/contracts)
GnosisSafe: [0xA0232BAab476eE456446f25585A696E35942b657](https://volta-explorer.energyweb.org/address/0xa0232baab476ee456446f25585a696e35942b657/contracts)
StateChannelModule: [0x7d6FCA9ceA7d3C14d6acEE43DCD91A3aa2b701eB](https://volta-explorer.energyweb.org/address/0x7d6fca9cea7d3c14d6acee43dcd91a3aa2b701eb/contracts)
DailyLimitModule: [0xe490bA5F4a65CE92826DF20d76591146717Fa8B6](https://volta-explorer.energyweb.org/address/0xe490ba5f4a65ce92826df20d76591146717fa8b6/contracts)
SocialRecoveryModule: [0x88e7F8aC4057e5e175119d8bf881E3B63bb403Bd](https://volta-explorer.energyweb.org/address/0x88e7f8ac4057e5e175119d8bf881e3b63bb403bd/contracts)
WhitelistModule: [0x1aE4Ce2E4F93F81d490F922829fc3376F03B9a5C](https://volta-explorer.energyweb.org/address/0x1ae4ce2e4f93f81d490f922829fc3376f03b9a5c/contracts)

After deploying the contracts, I try connecting to them using the CLI, but run into the following error:

```
(venv) ➜  safe-cli git:(master) ✗ python safe_cli.py 0xA0232BAab476eE456446f25585A696E35942b657 https://volta-rpc.energyweb.org

  ____                 _       ____         __         ____ _     ___ 
 / ___|_ __   ___  ___(_)___  / ___|  __ _ / _| ___   / ___| |   |_ _|
| |  _| '_ \ / _ \/ __| / __| \___ \ / _` | |_ / _ \ | |   | |    | | 
| |_| | | | | (_) \__ \ \__ \  ___) | (_| |  _|  __/ | |___| |___ | | 
 \____|_| |_|\___/|___/_|___/ |____/ \__,_|_|  \___|  \____|_____|___|
                                                                      

Loading Safe information...
Traceback (most recent call last):
  File "safe_cli.py", line 28, in <module>
    safe_operator.print_info()
  File "/Users/bagaricj/Code/safe-cli/safe_cli/safe_operator.py", line 410, in print_info
    for key, value in dataclasses.asdict(self.safe_cli_info).items():
  File "/Users/bagaricj/Code/safe-cli/safe_cli/safe_operator.py", line 129, in safe_cli_info
    self._safe_cli_info = self.refresh_safe_cli_info()
  File "/Users/bagaricj/Code/safe-cli/safe_cli/safe_operator.py", line 155, in refresh_safe_cli_info
    self._safe_cli_info = self.get_safe_cli_info()
  File "/Users/bagaricj/Code/safe-cli/safe_cli/safe_operator.py", line 438, in get_safe_cli_info
    safe_info = safe.retrieve_all_info()
  File "/Users/bagaricj/Code/safe-cli/venv/lib/python3.8/site-packages/gnosis/safe/safe.py", line 538, in retrieve_all_info
    results = self.ethereum_client.batch_call([
  File "/Users/bagaricj/Code/safe-cli/venv/lib/python3.8/site-packages/gnosis/eth/ethereum_client.py", line 820, in batch_call
    return self.batch_call_custom(payloads, raise_exception=raise_exception, block_identifier=block_identifier)
  File "/Users/bagaricj/Code/safe-cli/venv/lib/python3.8/site-packages/gnosis/eth/ethereum_client.py", line 786, in batch_call_custom
    raise ValueError(f'Errors returned {errors}')
ValueError: Errors returned ["`getOwners`: {'code': -32015, 'message': 'VM execution error.', 'data': 'Bad instruction fe'}"]
```

Am I doing something wrong? Did I miss some initialization?

**Comment by Uxio0** [comment]
Hi @JosephBagaric , that's expected. You are using the `Safe Master Copy address`, that's not supposed to be used. The right way to use the Safe is having a proxy pointing to that Safe Master Copy, the `ProxyFactory` would be a good way to achieve that: https://docs.gnosis.io/safe/docs/contracts_architecture/#4-proxy
