### ISSUE TITLE
Auto execute transactions posted to transaction service

### ISSUE THREAD

**Issue by reader31** [gnosis/safe-cli#38]
Hi
I have a safe which requires only one out of the two owners to approve a transaction.
I'm trying to sign and post a safe tx using the safe-cli from one of the owner accounts, to the gnosis transaction service address here,
https://safe-transaction.mainnet.gnosis.io/api/v1/safes/{self.address}/multisig-transactions/

Currently the posted safe transaction shows up on the safe UI in the web app and I need to login to the safe webapp to manually execute it each time.
Is there a way for me to post my safe transaction from the command line such that it auto executes as soon as I post it to the transaction service, with out me having to manually execute it via the Safe web app UI?

since the transaction is already signed and posted by one of the owners I want it to auto execute directly.

**Comment by Uxio0** [comment]
Hi,

If you don't use `--tx-service` tx will be executed right away 🙂

**Comment by reader31** [comment]
Gr8...thx for the input.
