### ISSUE TITLE
there is a bug!

### ISSUE THREAD

**Issue by zrock23** [gnosis/safe-cli#39]
After source venv/bin/activate && pip install -r requirements.txt there is a bug!

**Comment by Uxio0** [comment]
What bug?

**Comment by zrock23** [comment]
Running setup.py install for pyethash ... error
    ERROR: Command errored out with exit status 1:
     command: 'c:\users\petar toshev\safe-cli\venv\scripts\python.exe' -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\Petar Toshev\\AppData\\Local\\Temp\\pip-install-s17fj1bo\\pyethash_92306f88d0f44b699647960f42a80fa4\\setup.py'"'"'; __file__='"'"'C:\\Users\\Petar Toshev\\AppData\\Local\\Temp\\pip-install-s17fj1bo\\pyethash_92306f88d0f44b699647960f42a80fa4\\setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\Petar Toshev\AppData\Local\Temp\pip-record-1w5lla_y\install-record.txt' --single-version-externally-managed --compile --install-headers 'c:\users\petar toshev\safe-cli\venv\include\site\python3.9\pyethash'
         cwd: C:\Users\Petar Toshev\AppData\Local\Temp\pip-install-s17fj1bo\pyethash_92306f88d0f44b699647960f42a80fa4\
    Complete output (21 lines):
    running install
    running build
    running build_ext
    building 'pyethash' extension
    creating build
    creating build\temp.win-amd64-3.9
    creating build\temp.win-amd64-3.9\Release
    creating build\temp.win-amd64-3.9\Release\src
    creating build\temp.win-amd64-3.9\Release\src\libethash
    creating build\temp.win-amd64-3.9\Release\src\python
    C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Tools\MSVC\14.28.29910\bin\HostX86\x64\cl.exe /c /nologo /Ox /W3 /GL /DNDEBUG /MD -Ic:\users\petar toshev\safe-cli\venv\include -IC:\Users\Petar Toshev\AppData\Local\Programs\Python\Python39\include -IC:\Users\Petar Toshev\AppData\Local\Programs\Python\Python39\include -IC:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Tools\MSVC\14.28.29910\include -IC:\Program Files (x86)\Windows Kits\NETFXSDK\4.8\include\um -IC:\Program Files (x86)\Windows Kits\10\include\10.0.19041.0\ucrt -IC:\Program Files (x86)\Windows Kits\10\include\10.0.19041.0\shared -IC:\Program Files (x86)\Windows Kits\10\include\10.0.19041.0\um -IC:\Program Files (x86)\Windows Kits\10\include\10.0.19041.0\winrt -IC:\Program Files (x86)\Windows Kits\10\include\10.0.19041.0\cppwinrt /Tcsrc/libethash/internal.c /Fobuild\temp.win-amd64-3.9\Release\src/libethash/internal.obj -Isrc/ -std=gnu99 -Wall
    cl : Command line warning D9002 : ignoring unknown option '-std=gnu99'
    internal.c
    C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Tools\MSVC\14.28.29910\bin\HostX86\x64\cl.exe /c /nologo /Ox /W3 /GL /DNDEBUG /MD -Ic:\users\petar toshev\safe-cli\venv\include -IC:\Users\Petar Toshev\AppData\Local\Programs\Python\Python39\include -IC:\Users\Petar Toshev\AppData\Local\Programs\Python\Python39\include -IC:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Tools\MSVC\14.28.29910\include -IC:\Program Files (x86)\Windows Kits\NETFXSDK\4.8\include\um -IC:\Program Files (x86)\Windows Kits\10\include\10.0.19041.0\ucrt -IC:\Program Files (x86)\Windows Kits\10\include\10.0.19041.0\shared -IC:\Program Files (x86)\Windows Kits\10\include\10.0.19041.0\um -IC:\Program Files (x86)\Windows Kits\10\include\10.0.19041.0\winrt -IC:\Program Files (x86)\Windows Kits\10\include\10.0.19041.0\cppwinrt /Tcsrc/libethash/io.c /Fobuild\temp.win-amd64-3.9\Release\src/libethash/io.obj -Isrc/ -std=gnu99 -Wall
    cl : Command line warning D9002 : ignoring unknown option '-std=gnu99'
    io.c
    C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Tools\MSVC\14.28.29910\bin\HostX86\x64\cl.exe /c /nologo /Ox /W3 /GL /DNDEBUG /MD -Ic:\users\petar toshev\safe-cli\venv\include -IC:\Users\Petar Toshev\AppData\Local\Programs\Python\Python39\include -IC:\Users\Petar Toshev\AppData\Local\Programs\Python\Python39\include -IC:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Tools\MSVC\14.28.29910\include -IC:\Program Files (x86)\Windows Kits\NETFXSDK\4.8\include\um -IC:\Program Files (x86)\Windows Kits\10\include\10.0.19041.0\ucrt -IC:\Program Files (x86)\Windows Kits\10\include\10.0.19041.0\shared -IC:\Program Files (x86)\Windows Kits\10\include\10.0.19041.0\um -IC:\Program Files (x86)\Windows Kits\10\include\10.0.19041.0\winrt -IC:\Program Files (x86)\Windows Kits\10\include\10.0.19041.0\cppwinrt /Tcsrc/libethash/io_win32.c /Fobuild\temp.win-amd64-3.9\Release\src/libethash/io_win32.obj -Isrc/ -std=gnu99 -Wall
    cl : Command line warning D9002 : ignoring unknown option '-std=gnu99'
    io_win32.c
    c1: fatal error C1083: Cannot open source file: 'src/libethash/io_win32.c': No such file or directory
    error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\BuildTools\\VC\\Tools\\MSVC\\14.28.29910\\bin\\HostX86\\x64\\cl.exe' failed with exit code 2
    ----------------------------------------
ERROR: Command errored out with exit status 1: 'c:\users\petar toshev\safe-cli\venv\scripts\python.exe' -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\Petar Toshev\\AppData\\Local\\Temp\\pip-install-s17fj1bo\\pyethash_92306f88d0f44b699647960f42a80fa4\\setup.py'"'"'; __file__='"'"'C:\\Users\\Petar Toshev\\AppData\\Local\\Temp\\pip-install-s17fj1bo\\pyethash_92306f88d0f44b699647960f42a80fa4\\setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\Petar Toshev\AppData\Local\Temp\pip-record-1w5lla_y\install-record.txt' --single-version-externally-managed --compile --install-headers 'c:\users\petar toshev\safe-cli\venv\include\site\python3.9\pyethash' Check the logs for full command output.

**Comment by Uxio0** [comment]
That's a Windows issue not related to the `safe-cli`, looks related to `pyethash`.
