### ISSUE TITLE
c1: fatal error C1083: Cannot open source file: 'src/libethash/io_win32.c'

### ISSUE THREAD

**Issue by jmchale22** [gnosis/safe-cli#56]
**Describe the bug**
Hi, A gnosis developer said to use safe-cli to access funds in the event the website is down.  I cannot get safe-cli to install properly on Windows.  Is this intended/supported for  Windows?
![safecli_error](https://user-images.githubusercontent.com/83552306/127724261-0552756e-0b98-4e14-b4aa-f5718f205846.jpg)

**To Reproduce**
install git bash, visual c++ runtime library, notepad++, 7zip
git clone https://github.com/gnosis/safe-cli.git
cd safe-cli
stat venv 2>/dev/null || python -m venv venv
source venv/**bin**/activate && pip install -r requirements.txt

This last line errors due to no "bin" folder on windows, so I changed the line to:
source venv/**Scripts**/activate && pip install -r requirements.txt

After changing to Scripts rather than bin, I see this message:
I see message "c1: fatal error C1083: Cannot open source file: 'src/libethash/io_win32.c'"

Before getting to this point, I had,10+ errors where I had to use pip install to install something not present, and had to get two wheel files.

**Expected behavior**
To finish the install without error.

**Comment by Uxio0** [comment]
Hi, it's not tested in Windows, but that error looks like more like an issue with the dependencies rather than with `safe-cli`: https://ethereum.stackexchange.com/questions/90769/unable-to-install-web3tester-cannot-open-source-file-src-libethash-io-wi

**Comment by Uxio0** [comment]
Could you try using https://docs.microsoft.com/en-us/windows/wsl/install-win10 ?
