### ISSUE TITLE
Delegates management

### ISSUE THREAD

**Issue by abarmat** [gnosis/safe-cli#57]
# What is needed?
Be able to list, add and remove delegates from the Safe CLI through the transaction-service.

# Background
I recently found out about the delegates features in the Safe Transaction Service. However, I didn't find an easy way to set it apart from manually crafting the http payload and signing. I was needing it for a use case where I don't want to expose a private key of an owner from a backend service.

# Related issues
I forked the repo and wrote an implementation https://github.com/abarmat/safe-cli/commits/manage-delegates for my own use. It is something that you might want to include, not sure if it was a planned feature.

**Comment by Uxio0** [comment]
Hi @abarmat, it was something planned but still not implemented, I used your really good implementation with some minor adjustments. Feel free to send more PRs if you keep hacking on the Safe-CLI!
