### ISSUE TITLE
Add "info" command.

### ISSUE THREAD

**Issue by tschubotz** [gnosis/safe-cli#6]
Feature request:
When checking out a Safe, it would be great to have a command like "info" or so, that just prints out network, mastercopy, owners, balance, nonce.
I know all this is in the footer, but that's cut off.

I also wouldn't mind if all this is printed out once after the Safe was loaded :)

**Comment by tschubotz** [comment]
Also the following would be interesting imo.
- ETH balance
- Link to Safe on etherscan in order to be able to switch  faster to etherscan with all txs.

**Comment by tschubotz** [comment]
ah, maybe I should read the open issues before. Some of the things I mention are probably part of #1 ;)

**Comment by Uxio0** [comment]
Don't worry, I will keep this issue and close the other one

**Comment by Uxio0** [comment]
Done, that's the output of the info command. Feel free to close the issue if you are ok with it @tschubotz 

```
safe-cli ❯ 0x7eA27faE68abbf0f2f0d71c17d21E4F2A3761108 > info                                          
Address=0x7eA27faE68abbf0f2f0d71c17d21E4F2A3761108
Nonce=7
Threshold=1
Owners=['0x5aC255889882aCd3da2aA939679E3f3d4cea221e']
Master_copy=0x34CfAC646f301356fAa8B21e94227e3583Fe3F5F
Fallback_handler=0x0000000000000000000000000000000000000000
Balance_ether=0.199999999999999916
Version=1.1.1
Safe Tx Service=https://safe-transaction.rinkeby.gnosis.io/api/v1/safes/0x7eA27faE68abbf0f2f0d71c17d21E4F2A3761108/transactions/
Etherscan=https://rinkeby.etherscan.io/address/0x7eA27faE68abbf0f2f0d71c17d21E4F2A3761108
```

**Comment by tschubotz** [comment]
Beautiful, thanks! Also nice idea with the tx service link!
