### ISSUE TITLE
Bep 20 BUSD token transfer.

### ISSUE THREAD

**Issue by adrian97gl** [gnosis/safe-cli#65]
Hello,

I had a problem right here and i don't know how to solve it.

How I could send BUSD from an account to another using cli ?

**Comment by Uxio0** [comment]
Using the command `send_erc20`. If there's an error please provide the terminal output (hiding you Safe address if you want) so we can debug it

**Comment by adrian97gl** [comment]
Hello @Uxio0 the problem was solved using the send_erc20 with checksum of BUSD token. Thank you for support !
