### ISSUE TITLE
Can't send to tx-service with delegate

### ISSUE THREAD

**Issue by philipcmonk** [gnosis/safe-cli#68]
**Describe the bug**
When sending to tx-service, delegates don't sign the request, causing it to fail.

**To Reproduce**
1. Add delegate to safe
2. Exit and come back in, then load the delegate
3. Try to send a tx (I used `send_custom`) with `--tx-service` (after running `tx-service`)
4. It fails with `Error posting transaction: b'{"signature":["This field may not be null."]}'`

**Expected behavior**
You should be able to send txs to the safe transaction service with a delegate.

**Additional context**
It works correctly if I comment out this line:

https://github.com/gnosis/safe-cli/blob/445cf136df76fc9053d413dc62b424082ac1d03c/safe_cli/safe_operator.py#L600

Unfortunately, this would break if you load non-owner and non-delegate addresses.

**Comment by Uxio0** [comment]
It looks indeed like a problem on our side, thanks for the detailed report!
