### ISSUE TITLE
Transaction history

### ISSUE THREAD

**Issue by tschubotz** [gnosis/safe-cli#7]
If I imagine to use the cli instead of etherscan when checking out a Safe address, I felt like i was missing:

- ETH balance
- ERC20 token balances
- Transaction history (as a first step, there could be a link to the tx on etherscan also)

**Comment by Uxio0** [comment]
@tschubotz This would be a first draft of the transaction history, still missing ETH/ERC20 balance

![image](https://user-images.githubusercontent.com/6909403/74579669-90241e00-4f9c-11ea-8103-299cf62d88a5.png)

**Comment by tschubotz** [comment]
I like it already! Especially that dataDecoded column :)

**Comment by Uxio0** [comment]
> I like it already! Especially that dataDecoded column :)

It's also red for failed transactions and yellow for pending ones :)

I may refactor the command under `tx-service history` so you can also do `tx-service sign <safeTxHash>` or `tx-service execute <safeTxHash>`

**Comment by Uxio0** [comment]
Balances are available under `balances` command
